[package]
name = "clyntis"
version.workspace = true
edition.workspace = true
license.workspace = true
[dependencies]
meta-core.workspace = true
meta-runtime.workspace = true
tokio-util.workspace = true
meta-config.workspace = true
meta-platform.workspace = true
anyhow.workspace = true
tokio.workspace = true
clap = { version = "4", features = ["derive", "env"] }
base64.workspace = true
zeroize.workspace = true
serde_json.workspace = true
tracing.workspace = true
rpassword = "7"

[dev-dependencies]
tempfile = "3"
