[package]
name = "meta-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
[lib]
crate-type = ["rlib", "staticlib", "cdylib"]
[dependencies]
meta-core.workspace = true
meta-config.workspace = true
meta-platform.workspace = true
tokio.workspace = true
serde_json.workspace = true
anyhow.workspace = true
async-trait.workspace = true
socket2.workspace = true
[dev-dependencies]
smoltcp = { version = "=0.12.0", default-features = false, features = ["std", "medium-ip", "proto-ipv4", "socket-icmp"] }
